# Generated by Django 2.2.5 on 2019-10-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideline',
            name='title',
        ),
    ]
