# Generated by Django 2.2.7 on 2019-11-20 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetugasInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.PositiveIntegerField(choices=[(0, 'laki-laki'), (1, 'perempuan')])),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('tipe', models.PositiveIntegerField(choices=[(0, 'pasien'), (1, 'petugas'), (2, 'dokter'), (3, 'apoteker')])),
                ('nomor_pegawai', models.CharField(blank=True, max_length=13)),
                ('surat_tugas', models.ImageField(blank=True, upload_to='akun/media/petugas/surat_tugas')),
                ('profil', models.ImageField(blank=True, upload_to='akun/media/petugas/profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PetugasInfo',
            },
        ),
        migrations.CreateModel(
            name='PasienInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.PositiveIntegerField(choices=[(0, 'laki-laki'), (1, 'perempuan')])),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('tipe', models.PositiveIntegerField(choices=[(0, 'pasien'), (1, 'petugas'), (2, 'dokter'), (3, 'apoteker')])),
                ('nomor_bpjs', models.CharField(blank=True, max_length=13)),
                ('bpjs', models.ImageField(blank=True, upload_to='akun/media/pasien/bpjs')),
                ('rujukan', models.ImageField(blank=True, upload_to='akun/media/pasien/rujukan')),
                ('profil', models.ImageField(blank=True, upload_to='akun/media/pasien/profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PasienInfo',
            },
        ),
        migrations.CreateModel(
            name='DokterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.PositiveIntegerField(choices=[(0, 'laki-laki'), (1, 'perempuan')])),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('tipe', models.PositiveIntegerField(choices=[(0, 'pasien'), (1, 'petugas'), (2, 'dokter'), (3, 'apoteker')])),
                ('nomor_pegawai', models.CharField(blank=True, max_length=13)),
                ('surat_tugas', models.ImageField(blank=True, upload_to='akun/media/dokter/surat_tugas')),
                ('profil', models.ImageField(blank=True, upload_to='akun/media/dokter/profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DokterInfo',
            },
        ),
        migrations.CreateModel(
            name='ApotekerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.PositiveIntegerField(choices=[(0, 'laki-laki'), (1, 'perempuan')])),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('tipe', models.PositiveIntegerField(choices=[(0, 'pasien'), (1, 'petugas'), (2, 'dokter'), (3, 'apoteker')])),
                ('nomor_pegawai', models.CharField(blank=True, max_length=13)),
                ('surat_tugas', models.ImageField(blank=True, upload_to='akun/media/apoteker/surat_tugas')),
                ('profil', models.ImageField(blank=True, upload_to='akun/media/apoteker/profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ApotekerInfo',
            },
        ),
    ]
