# Generated by Django 2.0.1 on 2019-11-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'petugas'), (2, 'dokter'), (3, 'apoteker')], default=0),
        ),
    ]
